#
# Copyright (c) 2010 rPath, Inc.
#
# All rights reserved.
#

SUBDIRS = bootloader generators mkinitrd
override DIR=jobslave

python_files = $(wildcard *.py)


all: default-all

install: default-install

clean: default-clean


include ../Make.rules
include ../Make.defs
