#
# Copyright (c) 2009 rPath, Inc.
#
# All rights reserved.
#

python_files = $(wildcard *.py)


all: default-all

install: default-install

clean: default-clean


include ../../Make.rules
include ../../Make.defs
